language: python
python:
  - "2.7"
# command to install dependencies
# install: "pip install -r requirements.txt"
install: "pip install ."
# command to run tests
script: "python -m unittest discover mimicry/test"
